// Auto-generated by scripts/build-docs.mjs
export const docsContent = {
  "docs/quick-start": `
# Quick Start

RunDoc 的最小工作流不是先整理 inbox，而是先绑定项目并扫描变更。

## 1. 初始化项目结构

在项目根目录准备：

\`\`\`text
docs/
  00-positioning/
  01-product/
  02-business/
  03-technical/
  04-ai/
  05-decisions/
  06-ops/
  07-archive/

.rundoc/
  config.yml
  prompts/
  state/
  reports/
\`\`\`

## 2. 运行命令闭环

\`\`\`bash
rundoc init
rundoc scan
rundoc write
rundoc check
rundoc commit
\`\`\`

- \`scan\`: 从 \`last_commit..HEAD\` 生成变更影响报告
- \`write\`: 更新受影响 Markdown 文档
- \`check\`: 检查冲突/缺失/过期
- \`commit\`: 生成可审阅提交

## 3. 报告产物

每次扫描应产出运行报告：

\`\`\`text
.rundoc/reports/YYYY-MM-DD-run.md
\`\`\`

报告至少包含：

- 本次项目变化摘要
- 受影响文档清单
- 建议更新项
- 未决冲突与人工确认点

## 4. 文档站本地开发（可选）

当前仓库包含文档站 UI，可用于浏览 \`docs/\`：

\`\`\`bash
npm install
npm run build
npm run dev
\`\`\`
`,
  "docs/overview": `
# Overview

RunDoc 是一个项目变更驱动的文档自动维护系统。

它绑定项目仓库，持续感知代码与配置变化，判断哪些文档受影响，并自动生成可审阅的 Markdown 更新。

## 核心定义

RunDoc 不以“人工整理材料”为主流程，不要求先手工产出 \`meeting-notes.md\` 或 \`manual-notes.md\` 再汇总。

RunDoc 的主流程是：

\`\`\`text
项目变化 -> 影响分析 -> 文档补丁 -> 审核合并
\`\`\`

## 输入与输出

输入（项目状态）：

- Git diff
- Commit history
- GitLab Issue / MR（可选）
- 现有 \`docs/\`
- \`.rundoc/config.yml\`
- 可选人工材料（只作为补充）

输出（文档变更资产）：

- \`docs/**/*.md\` 更新
- \`docs/04-ai/*\` AI 上下文更新
- 文档一致性检查结果
- \`.rundoc/reports/*.md\` 扫描报告
- Draft commit / MR 建议

## 运行闭环

\`\`\`text
Detect -> Understand -> Map -> Patch -> Commit
\`\`\`

1. Detect: 发现项目变化  
2. Understand: 理解变化影响  
3. Map: 映射到具体文档  
4. Patch: 生成 Markdown 补丁  
5. Commit: 生成可审核提交
`,
  "docs/architecture": `
# Architecture

RunDoc 分为两层：项目变更引擎（核心）和文档站渲染层（当前已实现）。

## 1) Project Watch 引擎（核心）

\`\`\`text
Git / Repo State
  -> Detect (diff/commit/MR)
  -> Understand (impact analysis)
  -> Map (doc targets)
  -> Patch (markdown updates)
  -> Commit (reviewable change)
\`\`\`

### Detect

读取 \`last_commit..HEAD\` 的变更，覆盖代码、配置、数据库脚本、部署脚本与 \`docs/\` 自身变化。

### Understand

基于路径、提交语义和规则判断变更影响域，例如：

- \`frontend/**\` 影响产品页面文档
- \`backend/**\` 影响 API/技术文档
- \`schema.sql\` 影响数据模型文档
- \`docker-compose.yml\` 影响部署运维文档

### Map

将影响域映射到文档目标路径（优先更新已有文档），并生成待修改清单。

### Patch

对目标 Markdown 生成最小补丁，不重写整篇文档。

### Commit

输出可审阅的分支、提交与报告，不直接跳过人工审核。

## 2) 文档站渲染层（当前）

\`\`\`text
docs/**/*.md
  -> scripts/build-docs.mjs
  -> src/content/docs-content.ts
  -> src/content/search-index.json
  -> React documentation app
\`\`\`

渲染层负责阅读体验（导航、搜索、TOC），不负责变更感知。
`,
  "docs/reference/roadmap": `
# Roadmap

RunDoc 以“项目变化驱动文档更新”为主线推进。

## V0.1 Project Docs Skeleton

- 标准化 \`docs/\` 分层目录
- 初始化 \`.rundoc/config.yml\`
- 建立 \`.rundoc/state/\` 与 \`.rundoc/reports/\`

## V0.2 Diff Scan

- 实现 \`rundoc scan\`
- 读取 \`last_commit..HEAD\`
- 生成影响分析报告

## V0.3 Markdown Patch

- 实现 \`rundoc write\`
- 对受影响文档生成最小补丁
- 优先更新已有文档

## V0.4 AI Context Refresh

- 自动刷新 \`docs/04-ai/\` 核心上下文文档
- 输出 code-change map / acceptance checklist / known inconsistencies

## V0.5 GitLab Integration

- 读取 Issue / MR 元数据
- 在 MR 生成文档影响评论
- 对“代码变更未同步文档”给出提醒
`,
  "docs/reference/content-model": `
# Content Model

RunDoc 的数据模型分三层：项目变更、文档目标、补丁产物。

## 1) Change Event

\`\`\`text
change_id
base_commit
head_commit
changed_paths[]
commit_messages[]
detected_at
\`\`\`

## 2) Impact Mapping

\`\`\`text
change_id
impact_domain         # product / technical / ai / ops / business / decisions
reason
target_docs[]
confidence
needs_human_review
\`\`\`

## 3) Document Patch

\`\`\`text
doc_path
patch_type            # update / create / conflict
summary
diff_preview
applied
\`\`\`

## 4) Generated Report

\`\`\`text
run_id
report_path
affected_docs[]
conflicts[]
followups[]
\`\`\`

## 5) 站点渲染模型（已有）

\`\`\`text
doc_id
path
title
section
tags
summary
headings
chunks
links
updated_at
source_hash
\`\`\`

以上模型把“文档站渲染”与“项目变更感知”拆开，避免把 RunDoc 降级成纯静态发布器。
`,
  "docs/guide/writing-docs": `
# Writing Docs

Write documents in plain Markdown.

Use a single \`#\` heading for the page title. Use frontmatter when the navigation or search title should differ from the visible heading.

\`\`\`md
---
title: Pricing Rules
---

# Pricing Rules
\`\`\`

## Good Team Documents

Good RunDoc documents should be:

- Sourceable: every rule has a clear owner or origin.
- Addressable: each document has a stable path.
- Chunkable: headings divide content into useful sections.
- Actionable: explain what someone should do, not only what exists.
- AI-readable: avoid vague references such as "this", "that", or "above" when a named concept is clearer.

## Markdown Links

Prefer relative links between documents:

\`\`\`md
[Architecture](../architecture.md)
\`\`\`

RunDoc resolves internal Markdown links into documentation routes.
`,
  "docs/guide/navigation": `
# Navigation

RunDoc navigation is currently configured in \`src/locales/zh-CN.json\`.

Each navigation section has a title and a list of items.

\`\`\`json
{
  "title": "AI-native",
  "items": [
    { "title": "API Contract", "path": "/docs/ai/api-contract", "label": "API" }
  ]
}
\`\`\`

## Route Rules

Markdown files map to routes by path:

\`\`\`text
docs/overview.md -> /docs/overview
docs/ai/api-contract.md -> /docs/ai/api-contract
\`\`\`

The home route \`/\` is reserved for the landing page.
`,
  "docs/07-archive/README": `
# Archive

存放失效或历史版本文档。

归档文档应保留来源与失效原因，避免与正式文档混淆。
`,
  "docs/ai/design-principles": `
# AI Design Principles

RunDoc is designed for AI systems from the data model upward.

The goal is not to add a chatbot to a static site. The goal is to make team knowledge structured enough that AI can retrieve, cite, update, and validate it.

## Principles

1. Stable IDs over visual scraping.
2. Markdown source over generated HTML.
3. Explicit metadata over implicit page interpretation.
4. Document chunks over whole-page guessing.
5. Citation paths over ungrounded answers.
6. Project changes over manual inbox as primary trigger.
7. Update existing docs over generating detached summaries.

## Agent Behavior

An AI agent should be able to ask:

- Which documents exist?
- Which sections relate to this task?
- What changed since the previous build?
- Which source document supports this answer?
- Which documents need updates after a code or product change?
- What changed since last scan commit?
- Which exact Markdown files should be patched now?
`,
  "docs/ai/api-contract": `
# API Contract

RunDoc should expose AI-readable document interfaces.

The first repository version is static, but the API contract is documented early to keep system direction clear.

## Planned Endpoints

\`\`\`text
GET /api/docs/tree
GET /api/docs/doc/:id
GET /api/docs/search?q=
GET /api/docs/context?path=
GET /api/docs/related?path=
POST /api/docs/reindex
POST /api/rundoc/scan
POST /api/rundoc/write
POST /api/rundoc/check
POST /api/rundoc/commit
\`\`\`

## RunDoc Engine Response Shape

\`\`\`json
{
  "runId": "2026-05-20",
  "baseCommit": "a1b2c3d",
  "headCommit": "d4e5f6g",
  "changes": [
    {
      "path": "backend/routes/quotes.py",
      "type": "modified"
    }
  ],
  "impacts": [
    {
      "domain": "technical",
      "reason": "quotes API route changed",
      "targetDocs": [
        "docs/03-technical/api-routes.md"
      ],
      "confidence": 0.89
    }
  ],
  "conflicts": []
}
\`\`\`

## Document Response Shape

\`\`\`json
{
  "id": "docs/ai/api-contract.md",
  "path": "/docs/ai/api-contract",
  "title": "API Contract",
  "section": "AI-native",
  "headings": ["Planned Endpoints", "Document Response Shape"],
  "summary": "RunDoc should expose AI-readable document interfaces.",
  "sourceHash": "sha256:...",
  "updatedAt": "2026-05-20T00:00:00Z"
}
\`\`\`

## Context Response Shape

\`\`\`json
{
  "doc": {},
  "chunks": [
    {
      "id": "docs/ai/api-contract.md#planned-endpoints",
      "heading": "Planned Endpoints",
      "text": "GET /api/docs/tree..."
    }
  ],
  "links": []
}
\`\`\`
`,
  "docs/06-ops/deployment": `
# 部署与运维

记录部署配置、运行依赖、常见排障路径。

## 维护规则

1. 配置与脚本变更自动触发文档更新建议。
2. 部署步骤必须可复制执行。
3. 风险操作需要前置警告与回滚路径。
`,
  "docs/05-decisions/decision-log": `
# 决策记录

记录关键产品、技术与流程决策。

## 维护规则

1. 每条决策应包含背景、方案、结论、影响范围。
2. 决策变更应引用对应 commit / MR。
3. 失效决策应标记归档路径。
`,
  "docs/04-ai/known-inconsistencies": `
# 已知不一致

记录跨文档冲突或未收敛规则，供人工确认。

## 记录格式

- 冲突描述
- 涉及文档
- 建议处理方向
- 当前状态（open/confirmed/resolved）
`,
  "docs/04-ai/code-change-map": `
# Code Change Map

维护“代码变更 -> 文档影响”的映射结果。

## 记录字段

- 变更 commit 范围
- 影响域
- 目标文档路径
- 更新状态
- 人工确认点
`,
  "docs/04-ai/ai-context": `
# AI Context

供 AI coding agent 读取的项目压缩上下文入口。

## 更新规则

1. 仅由正式文档变更触发刷新。
2. 不直接引用临时聊天记录作为事实源。
3. 所有关键规则应能追溯到 \`docs/\` 正式文档与 commit。
`,
  "docs/04-ai/acceptance-checklist": `
# 验收清单

RunDoc 每次文档更新后用于快速验收。

## 检查项

- 是否覆盖本次受影响文档
- 是否仅做必要最小改动
- 是否存在跨文档规则冲突
- 是否标记需要人工确认的问题
`,
  "docs/03-technical/api-routes": `
# API 路由总览

记录后端接口、参数与行为边界。

## 维护规则

1. 接口变更由代码 diff 驱动文档更新。
2. 更新优先修改已有路由描述，不重复造新文档。
3. 接口兼容性变化必须记录迁移说明。
`,
  "docs/02-business/process-notes": `
# 业务流程说明

记录业务流、角色边界和交付约束。

## 维护规则

1. 业务流程变化应由项目变化触发更新。
2. 业务文档需要可追溯到需求、Issue 或 MR。
3. 与产品、技术或 AI 规则冲突时必须标记待确认。
`,
  "docs/01-product/page-specs": `
# 页面规格

记录当前产品页面行为与关键约束。

## 维护规则

1. 页面行为变化来自代码变更触发，不靠人工汇总。
2. RunDoc 只对受影响段落做最小更新。
3. 每次更新需要保留变更来源（commit / MR）。
`,
  "docs/00-positioning/overview": `
# 定位总览

RunDoc 是一个跟随项目变更自动维护 Markdown 文档的系统。

它不是资料收件箱，不依赖人工先整理输入文件。  
它直接读取项目状态变化，并更新正式文档。

## 核心闭环

\`\`\`text
Detect -> Understand -> Map -> Patch -> Commit
\`\`\`

## 输入

- Git diff
- Commit 历史
- GitLab Issue / MR（可选）
- 现有 \`docs/\`
- \`.rundoc/config.yml\`

## 输出

- \`docs/**/*.md\` 更新
- \`docs/04-ai/*\` AI 上下文更新
- \`.rundoc/reports/*.md\` 扫描报告
- 可审核的提交或 MR 草稿
`,
};