// Auto-generated by scripts/build-docs.mjs
export const docsContent = {
  "docs/quick-start": `
# Quick Start

Install dependencies and build the documentation site.

\`\`\`bash
npm install
npm run build
npm run dev
\`\`\`

RunDoc reads Markdown files from \`docs/\` and generates TypeScript content under \`src/content/\`.

## Add A Document

Create a Markdown file:

\`\`\`text
docs/guide/example.md
\`\`\`

Add it to navigation in:

\`\`\`text
src/locales/zh-CN.json
\`\`\`

Then rebuild:

\`\`\`bash
npm run build
\`\`\`

## Check Docs

\`\`\`bash
npm run check:docs
\`\`\`

The checker validates known routes and internal Markdown links.
`,
  "docs/overview": `
# Overview

RunDoc is an AI-native Markdown documentation system for running teams.

It keeps Markdown as the source of truth and turns a docs repository into a structured documentation site with navigation, search metadata, table of contents, and predictable document routes.

The product direction is simple:

- Keep writing in Markdown.
- Keep collaborating through Git.
- Make docs readable for humans.
- Make docs addressable and reliable for AI agents.

RunDoc should help a team keep decisions, product rules, SOPs, architecture notes, onboarding paths, and AI operating context in one coherent system.

## Why It Exists

Traditional static docs sites are good for publishing pages. Running teams need more than publishing.

They need documents that can be searched, referenced, checked, updated, and passed to AI systems without losing source identity or context.

RunDoc is designed around this boundary.

## Current Scope

The first version is a static React docs app:

- Markdown source in \`docs/\`
- Build-time content generation
- Search index generation
- Sidebar navigation from config
- Document pages with TOC and previous/next links

The AI API layer is documented before implementation so downstream projects can integrate against a stable model.
`,
  "docs/architecture": `
# Architecture

RunDoc uses a small static build pipeline.

\`\`\`text
docs/**/*.md
  -> scripts/build-docs.mjs
  -> src/content/docs-content.ts
  -> src/content/search-index.json
  -> React documentation app
\`\`\`

## Source Layer

Markdown files are the source of truth. Frontmatter may define document metadata such as \`title\`.

## Build Layer

The build script scans Markdown files, extracts headings, creates route keys, and generates a search index.

## App Layer

The React app renders:

- Home page
- Documentation layout
- Sidebar
- Header search
- Markdown body
- Page table of contents
- Previous and next navigation

## AI Layer

The planned AI layer should consume the same document graph generated at build time. It should not scrape rendered HTML.
`,
  "docs/reference/roadmap": `
# Roadmap

RunDoc starts as a static documentation system and grows toward an AI-readable team knowledge layer.

## Near Term

- Extract Markdown into typed content.
- Generate search index and route metadata.
- Provide a clean React documentation UI.
- Validate internal Markdown links.

## Next

- Generate document chunks.
- Generate JSON manifest for AI consumers.
- Add document freshness checks.
- Add API server mode.

## Later

- AI-assisted document updates.
- Change-impact detection.
- Source-cited answers.
- Team-specific reading paths.
`,
  "docs/reference/content-model": `
# Content Model

RunDoc documents should compile into a structured model.

\`\`\`text
doc_id
path
title
section
tags
summary
headings
chunks
links
updated_at
source_hash
\`\`\`

## Why This Matters

The content model is the shared contract between:

- the Markdown authoring workflow
- the rendered documentation site
- search
- future AI retrieval
- future validation jobs

If this model stays stable, teams can evolve the UI and API without changing how documents are written.
`,
  "docs/guide/writing-docs": `
# Writing Docs

Write documents in plain Markdown.

Use a single \`#\` heading for the page title. Use frontmatter when the navigation or search title should differ from the visible heading.

\`\`\`md
---
title: Pricing Rules
---

# Pricing Rules
\`\`\`

## Good Team Documents

Good RunDoc documents should be:

- Sourceable: every rule has a clear owner or origin.
- Addressable: each document has a stable path.
- Chunkable: headings divide content into useful sections.
- Actionable: explain what someone should do, not only what exists.
- AI-readable: avoid vague references such as "this", "that", or "above" when a named concept is clearer.

## Markdown Links

Prefer relative links between documents:

\`\`\`md
[Architecture](../architecture.md)
\`\`\`

RunDoc resolves internal Markdown links into documentation routes.
`,
  "docs/guide/navigation": `
# Navigation

RunDoc navigation is currently configured in \`src/locales/zh-CN.json\`.

Each navigation section has a title and a list of items.

\`\`\`json
{
  "title": "AI-native",
  "items": [
    { "title": "API Contract", "path": "/docs/ai/api-contract", "label": "API" }
  ]
}
\`\`\`

## Route Rules

Markdown files map to routes by path:

\`\`\`text
docs/overview.md -> /docs/overview
docs/ai/api-contract.md -> /docs/ai/api-contract
\`\`\`

The home route \`/\` is reserved for the landing page.
`,
  "docs/ai/design-principles": `
# AI Design Principles

RunDoc is designed for AI systems from the data model upward.

The goal is not to add a chatbot to a static site. The goal is to make team knowledge structured enough that AI can retrieve, cite, update, and validate it.

## Principles

1. Stable IDs over visual scraping.
2. Markdown source over generated HTML.
3. Explicit metadata over implicit page interpretation.
4. Document chunks over whole-page guessing.
5. Citation paths over ungrounded answers.

## Agent Behavior

An AI agent should be able to ask:

- Which documents exist?
- Which sections relate to this task?
- What changed since the previous build?
- Which source document supports this answer?
- Which documents need updates after a code or product change?
`,
  "docs/ai/api-contract": `
# API Contract

RunDoc should expose AI-readable document interfaces.

The first repository version is static, but the API contract is documented early to keep the system direction clear.

## Planned Endpoints

\`\`\`text
GET /api/docs/tree
GET /api/docs/doc/:id
GET /api/docs/search?q=
GET /api/docs/context?path=
GET /api/docs/related?path=
POST /api/docs/reindex
\`\`\`

## Document Response Shape

\`\`\`json
{
  "id": "docs/ai/api-contract.md",
  "path": "/docs/ai/api-contract",
  "title": "API Contract",
  "section": "AI-native",
  "headings": ["Planned Endpoints", "Document Response Shape"],
  "summary": "RunDoc should expose AI-readable document interfaces.",
  "sourceHash": "sha256:...",
  "updatedAt": "2026-05-20T00:00:00Z"
}
\`\`\`

## Context Response Shape

\`\`\`json
{
  "doc": {},
  "chunks": [
    {
      "id": "docs/ai/api-contract.md#planned-endpoints",
      "heading": "Planned Endpoints",
      "text": "GET /api/docs/tree..."
    }
  ],
  "links": []
}
\`\`\`
`,
};