import type { Project, Document, HistoryEntry } from './api';

export const mockProjects: Project[] = [
  {
    id: 'proj-1',
    slug_id: 'rundoc',
    name: 'RunDoc',
    description: 'AI-Native Markdown Docs for running teams. Build structured, searchable, AI-readable documentation from Markdown repositories.',
    git_repo_url: 'https://github.com/wang-h/rundoc',
    status: 'active',
    created_at: '2026-01-15T08:00:00Z',
    updated_at: '2026-05-20T10:30:00Z',
  },
  {
    id: 'proj-2',
    slug_id: 'runos-api',
    name: 'RunOS API',
    description: 'Backend API server for the RunOS platform. Handles authentication, project management, document storage, and AI agent orchestration.',
    git_repo_url: 'https://github.com/wang-h/runos-api',
    status: 'active',
    created_at: '2026-02-01T09:00:00Z',
    updated_at: '2026-05-22T14:15:00Z',
  },
  {
    id: 'proj-3',
    slug_id: 'editor-markdown',
    name: 'Editor Markdown',
    description: 'Shared Markdown editor component for RunOS. Supports split-view editing, syntax highlighting, and real-time preview.',
    git_repo_url: 'https://github.com/wang-h/editor-markdown',
    status: 'active',
    created_at: '2026-03-10T11:00:00Z',
    updated_at: '2026-05-23T09:00:00Z',
  },
  {
    id: 'proj-4',
    slug_id: 'runos-cli',
    name: 'RunOS CLI',
    description: 'Command-line interface for the RunOS platform. Project scaffolding, document generation, and AI agent commands.',
    git_repo_url: 'https://github.com/wang-h/runos-cli',
    status: 'archived',
    created_at: '2025-11-01T08:00:00Z',
    updated_at: '2026-04-15T16:00:00Z',
  },
];

export const mockDocuments: Record<string, Document[]> = {
  'proj-1': [
    {
      id: 'doc-1',
      slug_id: 'architecture',
      title: 'Architecture Overview',
      content: '# Architecture Overview\n\nRunDoc is built with a modular architecture...\n\n## System Components\n\n- **Frontend**: React + Vite + Ant Design\n- **Backend**: Node.js + Kysely + SQLite\n- **Editor**: Shared Markdown editor component\n\n## Data Flow\n\nDocuments flow from Markdown files through the build pipeline to the rendered site.',
      project_id: 'proj-1',
      parent_doc_id: null,
      status: 'published',
      position: 'a0',
      last_updated_by: 'hao',
      created_at: '2026-01-15T08:00:00Z',
      updated_at: '2026-05-20T10:00:00Z',
    },
    {
      id: 'doc-2',
      slug_id: 'quick-start',
      title: 'Quick Start Guide',
      content: '# Quick Start Guide\n\nGet started with RunDoc in 5 minutes.\n\n## Installation\n\n```bash\nnpm install\nnpm run dev\n```\n\n## Creating Your First Doc\n\nAdd Markdown files to the `docs/` directory.',
      project_id: 'proj-1',
      parent_doc_id: null,
      status: 'published',
      position: 'a1',
      last_updated_by: 'hao',
      created_at: '2026-01-16T09:00:00Z',
      updated_at: '2026-05-19T15:00:00Z',
    },
    {
      id: 'doc-3',
      slug_id: 'api-routes',
      title: 'API Routes',
      content: '# API Routes\n\n## Projects\n\n- `GET /api/projects` - List all projects\n- `POST /api/projects` - Create project\n\n## Documents\n\n- `GET /api/projects/:id/docs` - List documents',
      project_id: 'proj-1',
      parent_doc_id: null,
      status: 'draft',
      position: 'a2',
      last_updated_by: 'hao',
      created_at: '2026-03-20T10:00:00Z',
      updated_at: '2026-05-22T08:30:00Z',
    },
    {
      id: 'doc-4',
      slug_id: 'deployment',
      title: 'Deployment Guide',
      content: '# Deployment Guide\n\n## Docker\n\n```bash\ndocker build -t rundoc .\ndocker run -p 3000:3000 rundoc\n```',
      project_id: 'proj-1',
      parent_doc_id: null,
      status: 'draft',
      position: 'a3',
      last_updated_by: 'hao',
      created_at: '2026-04-10T11:00:00Z',
      updated_at: '2026-05-18T12:00:00Z',
    },
    {
      id: 'doc-5',
      slug_id: 'api-auth',
      title: 'Authentication Setup',
      content: '# Authentication Setup\n\nDetails on configuring OIDC authentication.\n\n## Sub-document\n\nThis doc demonstrates hierarchical nesting.',
      project_id: 'proj-1',
      parent_doc_id: 'doc-3',
      status: 'draft',
      position: 'a0',
      last_updated_by: 'hao',
      created_at: '2026-04-15T13:00:00Z',
      updated_at: '2026-05-21T09:00:00Z',
    },
  ],
  'proj-2': [
    {
      id: 'doc-6',
      slug_id: 'runos-api-overview',
      title: 'API Overview',
      content: '# API Overview\n\nBackend API server documentation.',
      project_id: 'proj-2',
      parent_doc_id: null,
      status: 'published',
      position: 'a0',
      last_updated_by: 'hao',
      created_at: '2026-02-01T09:00:00Z',
      updated_at: '2026-05-22T14:00:00Z',
    },
  ],
  'proj-3': [
    {
      id: 'doc-7',
      slug_id: 'editor-usage',
      title: 'Editor Usage',
      content: '# Editor Usage\n\nHow to use the shared Markdown editor.',
      project_id: 'proj-3',
      parent_doc_id: null,
      status: 'published',
      position: 'a0',
      last_updated_by: 'hao',
      created_at: '2026-03-10T11:00:00Z',
      updated_at: '2026-05-23T09:00:00Z',
    },
  ],
  'proj-4': [],
};

export const mockHistory: Record<string, HistoryEntry[]> = {
  'doc-1': [
    {
      id: 'hist-1',
      title: 'Architecture Overview',
      content: '# Architecture Overview\n\nRunDoc is built with a modular architecture...',
      changed_by: 'hao',
      change_summary: 'Added system components section',
      created_at: '2026-05-20T10:00:00Z',
    },
    {
      id: 'hist-2',
      title: 'Architecture Overview',
      content: '# Architecture Overview\n\nInitial version...',
      changed_by: 'hao',
      change_summary: 'Initial document creation',
      created_at: '2026-01-15T08:00:00Z',
    },
  ],
  'doc-3': [
    {
      id: 'hist-3',
      title: 'API Routes',
      content: '# API Routes\n\n## Projects...',
      changed_by: 'hao',
      change_summary: 'Added document endpoints',
      created_at: '2026-05-22T08:30:00Z',
    },
  ],
};
