import fs from 'fs';
import path from 'path';
import { fileURLToPath } from 'url';
import { glob } from 'glob';
import matter from 'gray-matter';

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);
const DOCS_DIR = path.resolve(__dirname, '../docs');
const OUTPUT_DIR = path.resolve(__dirname, '../src/content');
const OUTPUT_FILE = path.join(OUTPUT_DIR, 'docs-content.ts');
const SEARCH_INDEX_FILE = path.join(OUTPUT_DIR, 'search-index.json');

function filePathToRoute(relativePath) {
  const withoutExt = relativePath.replace(/\.md$/, '');
  if (withoutExt === 'overview') return '/docs/overview';
  return `/docs/${withoutExt}`;
}

function getSection(relativePath) {
  if (relativePath.startsWith('guide/')) return '使用指南';
  if (relativePath.startsWith('ai/')) return 'AI 原生';
  if (relativePath.startsWith('reference/')) return '参考';
  if (relativePath.startsWith('00-') || relativePath.startsWith('01-') || relativePath.startsWith('02-') ||
      relativePath.startsWith('03-') || relativePath.startsWith('04-') || relativePath.startsWith('05-') ||
      relativePath.startsWith('06-') || relativePath.startsWith('07-')) return '项目观察';
  if (['overview.md', 'quick-start.md', 'architecture.md'].includes(path.basename(relativePath))) return '开始';
  return '参考';
}

function extractHeadings(content) {
  const headings = [];
  const regex = /^#{1,3}\s+(.+)$/gm;
  let match;
  while ((match = regex.exec(content)) !== null) {
    headings.push(match[1].trim());
  }
  return headings;
}

async function build() {
  const files = await glob('**/*.md', {
    cwd: DOCS_DIR,
    ignore: ['**/node_modules/**'],
  });

  const docsContent = {};
  const searchEntries = [];

  for (const file of files) {
    const filePath = path.join(DOCS_DIR, file);
    const content = fs.readFileSync(filePath, 'utf-8');
    const { data: frontmatter, content: markdown } = matter(content);

    const route = filePathToRoute(file);
    const routeKey = route.replace(/^\//, '');
    const title = frontmatter.title || frontmatter.name || path.basename(file, '.md');

    docsContent[routeKey] = markdown;
    searchEntries.push({
      title,
      path: route,
      section: getSection(file),
      headings: extractHeadings(markdown),
    });
  }

  const lines = [
    '// Auto-generated by scripts/build-docs.mjs',
    'export const docsContent = {',
  ];

  for (const [key, content] of Object.entries(docsContent)) {
    const escaped = content.replace(/\\/g, '\\\\').replace(/`/g, '\\`').replace(/\${/g, '\\${');
    lines.push(`  ${JSON.stringify(key)}: \`${escaped}\`,`);
  }

  lines.push('};');

  fs.mkdirSync(OUTPUT_DIR, { recursive: true });
  fs.writeFileSync(OUTPUT_FILE, lines.join('\n'));
  fs.writeFileSync(SEARCH_INDEX_FILE, JSON.stringify(searchEntries, null, 2));
}

build().catch((err) => {
  console.error(err);
  process.exit(1);
});
